#---------------------------------------------------------
# Create PortReqTypeDesc
POST http://localhost:4004/v2/commonservice/PortReqTypeDescGASCService

{
               "requesttype":2,    
               "reqtypedesc":"Others" 
               
            }

### ------------------------------------------------------------------------
# Call Get Table
http://localhost:4004/v2/commonservice/DeleteTable()?request_id='SD20005577'&header=true


### ------------------------------------------------------------------------
# Call Get Table
http://localhost:4004/v2/commonservice/ReadComment()?request_id='R1623094329047'


### ------------------------------------------------------------------------
# Call getKaustReq
http://localhost:4004/v2/commonservice/getKaustReq()?kaust_id='100039'&sub_service_code='0202'&status=19



### ------------------------------------------------------------------------
# Create Request Table Entries
POST http://localhost:4004/v2/commonservice/ServiceTable
Content-Type: application/json

          {                
               "service_code":"0011" ,   
               "sub_service_code":"0009",
               "model_name":"KITS",      
               "table_name":"AVBooking",      
               "updation_type":"I"   
          }

### ------------------------------------------------------------------------
# Create Request Table Entries
DELETE  http://localhost:4004/v2/commonservice/ServiceTable(service_code='0008',sub_service_code='0008',model_name='KITS',table_name='Replenish')


### ------------------------------------------------------------------------
# Create Request Table Entries
PATCH  http://localhost:4004/v2/commonservice/ServiceTable(service_code='0011',sub_service_code='0009',model_name='KITS',table_name='AVBooking')
Content-Type: application/json

{                
                  
               "updation_type":"I"   
          }   

### ------------------------------------------------------------------------
# Create Request Table Entries
POST http://localhost:4004/v2/commonservice/ServiceTable
Content-Type: application/json

          {                
               "service_code":"0010" ,   
               "sub_service_code":"0018",
               "model_name":"KITS",      
               "table_name":"Vscan",      
               "updation_type":"I"   
          }          

### ------------------------------------------------------------------------
# Create Request Table Entries
GET http://localhost:4004/v2/commonservice/bpm_hr_appr(request_id='R1623080307885')/Set

### ------------------------------------------------------------------------
# Call ReadTERNotification
http://localhost:4004/v2/commonservice/ReadTERNotification()?request_id='R1624283814062'



### ------------------------------------------------------------------------
# Call UpdateStatus
http://localhost:4004/v2/commonservice/UpdateStatus()?request_id='0000000071'&status=3&userid='TST_EMPLOYEE'&header_x='X'&stage='s1'


### ------------------------------------------------------------------------
# Call ReadDepHRNotification
http://localhost:4004/v2/commonservice/ReadDepHRNotification()?request_id='0000000099'&sub_service_code='0302'

### ------------------------------------------------------------------------
# UpdateTable
http://localhost:4004/v2/commonservice/UpdateTable()?request_id='R1624368884007'&crmsrno='123'&equip_num=''

### ------------------------------------------------------------------------
# UpdateTable
http://localhost:4004/v2/commonservice/UpdateTable()?request_id='R1623130185748'&crmsrno=''&equip_num='L123'

### ------------------------------------------------------------------------
# Create Request Table Entries
POST http://localhost:4004/v2/commonservice/NeoConfig
Content-Type: application/json

          {                
            "applictaion":"KaustPrelanding",
            "type":"Avatar",       
            "id":"Avatar11",         
            "name":"Keep KAUST Safe",       
            "icon":"kaustsafe.svg",       
            "URL":"https://hse.kaust.edu.sa/Services/Pages/covid-19.aspx",      
            "order":1,      
            "student":"X",    
            "employee":"X",   
            "ptsa":"X",       
            "contractor":"X", 
            "external":"X",   
            "consultant":"X"  
          }

### ------------------------------------------------------------------------
# Create Request Table Entries
PATCH  http://localhost:4004/v2/commonservice/NeoConfig(applictaion='KaustHomepage',type='Avatar',id='Avatar1')
Content-Type: application/json

          {                   
            "URL":"https://cfdevelopment.cpp.cfapps.eu20.hana.ondemand.com/site?siteId=e831a011-0c3e-4a05-869b-877f3a9be19f#Shell-home"
          }          

### ------------------------------------------------------------------------
# Create Request Table Entries
PUT http://localhost:4004/v2/commonservice/NeoConfig(applictaion='KaustPrelanding',type='Avatar',id='Avatar1')
Content-Type: application/json

          {                
            "name":"Keep KAUST Safe",       
            "icon":"kaustsafe.svg",       
            "URL":"https://hse.kaust.edu.sa/Services/Pages/covid-19.aspx",      
            "order":1,      
            "student":"X",    
            "employee":"X",   
            "ptsa":"X",       
            "contractor":"X", 
            "external":"X",   
            "consultant":"X"  
          }


### ------------------------------------------------------------------------
# Create Request Table Entries
DELETE  http://localhost:4004/v2/commonservice/NeoConfig(applictaion='KaustHomepage',type='WorkFlow',id='WorkFlow2')

### ------------------------------------------------------------------------
# Create Request Table Entries
POST http://localhost:4004/v2/commonservice/NeoConfig
Content-Type: application/json

          {                
            "applictaion":"KaustHomepage",
            "type":"WorkFlow",       
            "id":"WorkFlow2",         
            "name":"Leave Approval",       
            "icon":"LeaveApproval.svg",       
            "URL":"",  
            "count":10,    
            "order":2,      
            "student":"X",    
            "employee":"X",   
            "ptsa":"X",       
            "contractor":"X", 
            "external":"X",   
            "consultant":"X"  
          }          


### ------------------------------------------------------------------------
# Data work center
POST http://localhost:4004/v2/kitservice/ReqHeader
Content-Type: application/json

{
                
                    "userid": "TST_EMPLOYEE",
                    "sub_service_code": "0056",
                    "service_code": "0016",
                    "status": 2 ,
                    "process_id": "",
                    "kaust_id": "100039",
                    "stage": "",
                    "last_name": "",
                    "first_name": "Abdulltm",
                    "middle_name": "",
                    "email": "Thajunniza.M.A@cognizant.com",
                    "expeditor": "",
                    "on_behalf": "",
                    "role": "",
                    "requestor_kaustid": "",
                    "onbehalfuserid": "",
                    "request_type": "",
                    "activity_type": "",
                    "flow": "",
                    "previous_step_process": "",
                "DCWPDetail":[
                    {
                      "sequence_number":1,
                      "r_first_name":"Thaj",  
                      "r_last_name":"Niza",   
                      "mobile_no":"9840799193",     
                      "start_date":"2021-05-15",    
                      "start_time":"14:58:35",    
                      "end_date":"2021-05-15",        
                      "end_time":"14:58:35",      
                      "bldglevel":"0",     
                      "bldgname":"Building-01 (SCC)",      
                      "rooms":"R-10 Corridor",         
                      "cold_wrk":"X",      
                      "hot_work":"X",      
                      "hse_wrk_permit":"34/HSE",
                      "dis_fire_supp":"X", 
                      "prop_f_name":"Rajneesh",   
                      "prop_l_name":"Pandey",   
                      "prop_kaust_id":"100381", 
                      "prop_userid":"PANDEYR",   
                      "prop_mobile":"+966544701045",   
                      "prop_dep":"ADM Service Automation & Collaboration" ,
                      "email":"rajneesh.pandey@kaust.edu.sa",       
                      "job_desc":"New request created for testing",    
                      "req_company":"Alfalak", 
                      "req_email":"haseeb.ahmad@kaust.edu.sa",   
                      "created_by":"HRILDP"
                    },
                    {
                      "sequence_number":2,
                      "r_first_name":"Mohamed",  
                      "r_last_name":"Zayd",   
                      "mobile_no":"9840799193",     
                      "start_date":"2021-05-15",    
                      "start_time":"14:58:35",    
                      "end_date":"2021-05-15",        
                      "end_time":"14:58:35",      
                      "bldglevel":"0",     
                      "bldgname":"Building-01 (SCC)",      
                      "rooms":"R-13 MDR",           
                      "cold_wrk":"X",      
                      "hot_work":"X",      
                      "hse_wrk_permit":"34/HSE",
                      "dis_fire_supp":"X", 
                      "prop_f_name":"Rajneesh",   
                      "prop_l_name":"Pandey",   
                      "prop_kaust_id":"100381", 
                      "prop_userid":"PANDEYR",   
                      "prop_mobile":"+966544701045",   
                      "prop_dep":"ADM Service Automation & Collaboration" ,
                      "email":"rajneesh.pandey@kaust.edu.sa",       
                      "job_desc":"New request created for testing",    
                      "req_company":"Alfalak", 
                      "req_email":"haseeb.ahmad@kaust.edu.sa",   
                      "created_by":"HRILDP"
                    }
                ],
                "DCWPManpower":[
            {
              "itm_sequence":1,
              "appl_name":"Mohammed Mutahhir",   
              "contrct_emp":"Employer", 
              "job_title":"Manager",   
              "kaust_id":"134567",    
              "dc_access_req":"Yes",
              "nationality":"Pakistani" 
               
},
       {
              "itm_sequence":2,
              "appl_name":"Abdul Mannan",   
              "contrct_emp":"Alfalak", 
              "job_title":"Web developer",   
              "kaust_id":"134689",    
              "dc_access_req":"Yes",
              "nationality":"Pakistani" 
               
}
                ],
                "log": [ {
                    "sequence_number": 1,
                    "status": 2,
                    "userid": "Abdulltm"}]
                
            }

#

### ------------------------------------------------------------------------
# Data work center
PATCH http://localhost:4004/v2/kitservice/ReqHeader/0000000061
Content-Type: application/json

{
                
                    "status": 3,                    
                "DCWPDetail":[
                    {
                      "sequence_number":1,     
                      "bldglevel":"5",     
                      "bldgname":"IT0",      
                      "rooms":"WS410"        
                      
                    }
                ],
                "DCWPManpower":[
            {
              "itm_sequence":1,
              "appl_name":"Mohammed Mutahhir",   
              "contrct_emp":"Employer1", 
              "job_title":"Manager1",   
              "kaust_id":"134567",    
              "dc_access_req":"Yes",
              "nationality":"Pakistani" 
               
},
       {
              "itm_sequence":2,
              "appl_name":"Abdul Mannan",   
              "contrct_emp":"Alfalak", 
              "job_title":"Web developer",   
              "kaust_id":"134689",    
              "dc_access_req":"Yes",
              "nationality":"Pakistani" 
               
}
                ],
                "log": [ {
                    "sequence_number": 1,
                    "timestamp": "8",
                    "status": 5,
                    "userid": "Abdulltm"}]
                
            }

#### ------------------------------------------------------------------------
# Data work center
PATCH http://localhost:4004/v2/kitservice/ReqHeader/0000000183
Content-Type: application/json

{
                
                    "status": 19                

                
            }

#### ------------------------------------------------------------------------
# Data work center
PATCH http://localhost:4004/v2/kitservice/AccessRequest/R1625048617112
Content-Type: application/json

{
                
                    "last_name":"Zayd" ,
                    "header":{
                      "last_name":"Zayd"  
                    }              

                
            }            


### ------------------------------------------------------------------------
# Delete Log
DELETE  http://localhost:4004/v2/kitservice/Log(request_id='0000000063',sequence_number=1,timestamp='8')

### ------------------------------------------------------------------------
# Patch Log
PATCH   http://localhost:4004/v2/gaservice/BirthCertificationSet(request_id='0000000099',sequence_number=2)
Content-Type: application/json

{
    "file_name": "HOSPITAL_CERTIFICATE_SARIYA_IBJEE.PDF"      
}

### ------------------------------------------------------------------------
# Patch Log
PATCH   http://localhost:4004/v2/gaservice/BirthCertificationSet(request_id='0000000099',sequence_number=1)
Content-Type: application/json

{
    "url": "http://sthdmpsrcs.kaust.edu.sa:01090,http://sthdmpsrcs.kaust.edu.sa:01090,http://sthdmpsrcs.kaust.edu.sa:01090"      
}